### ISSUE TITLE
 Request to Be Added as a Collaborator

### ISSUE THREAD

**Issue by abrarishere** [PassionOverPain/Tinotenda-Mhedziso#11]
Hello PassionOverPain,

I hope you're doing well. I am Abrar, and I have been following your this project with great interest. I find the work you're doing incredibly valuable and would love to contribute more actively to its development. 

Could you please add me as a collaborator on the repository? I am eager to help with responsive design and some styles related issue, and I believe I can make meaningful contributions to the project.

Thank you for considering my request. I look forward to the opportunity to work together!

Best regards,  
Abrar

**Comment by PassionOverPain** [comment]
Hey Abrar
I highly appreciate your interest on my project bro, it's still something small but I have recieved positive on the current version which is something I never thought would happen. I saw your PR and will definitely review and merge it as Responsive design is also another feat I need assistance with. **_Once Again, thank you for taking the time out of your life to work on this with me_** 🙏🏿😊
