### ISSUE TITLE
[UI/UX] Readability  issues

### ISSUE THREAD

**Issue by Qamreen22** [PassionOverPain/Tinotenda-Mhedziso#16]
The text on the homepage is not visible as it merges with the background, making it unreadable. Changing the font color, applying a blur effect to the background, or using glassmorphism could improve the visibility.
Furthermore, the button design could be improved by adding a background color to make it stand out more.

![image](https://github.com/user-attachments/assets/3a860891-c4b6-4c7c-9c66-7fb75cff8dfb)

**Comment by PassionOverPain** [comment]
Heyyy @Qamreen22 :)
Thanks for taking the time to review my website😌
I have taken your feedback and made a couple of graphical changes to **hopefully resolve** the problems you have outlined
Let me know what are your thoughts on the changes and please feel free to raise any other issue that you may encounter ~ _**Professional bug creator Tino**_

**Comment by Qamreen22** [comment]
@PassionOverPain It looks better now. I'm gonna close this issue.

**Comment by Qamreen22** [comment]
@PassionOverPain don't forget to make changes in the README

**Comment by PassionOverPain** [comment]
Done 👍🏿
